name: 'coverage'
on:
      pull_request:
      branches:
          - master
          - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install dependencies
            run: npm install
            working-directory: ./server

          - name: Jest Coverage Report
            uses: ArtiomTr/jest-coverage-report-action@v2
            with:
            working-directory: ./server